### PR TITLE
It 2.0

### PR DESCRIPTION
**Pull request by rmonroe**
This is a few of the bugs, so fuck around with alot of things to test.

- Delete a course (with nested relations)
- Disable a course
- Moved members out of dropdown for ease of view
- fixed Django vulnerability (run pip install -r requirements.txt)
- course description in a container
- if prof is a ta it will now show up in my courses
- email recipients will add scroll when too many
- Project cards will add ellipsis if to long for uniformity

### CODE REVIEW

**Comment by Kapn** [comment]
ScrollTitle href link doesn't work, the css is never found since its looking at /course/test123/css/ScrollTitle.css etc which doesn't exist. 
image
Needs to be changed to `<link rel="stylesheet" href="{% static 'css/ScrollTitle.css' %}">`

The course description container could probably be tweaked a bit but: 💯 

Django update seems safe as far as not breaking anything else. We should update to latest version asap though (2.1.5).

I've been playing with the course disable. I think its working but the dashboard etc isn't displaying them correctly. Additionally I think the sidebar should only display Active courses (edit: I see now that there is an inactive course dropdown under My Courses, so under 'My Courses' are only active courses I assume), as I see the sidebar as a quick way to access frequently used courses. In the 'All Courses' view, we should display/allow filtering of Active/Disabled/All Courses. Currently my dashboard looks like:
image

Delete Course works like a charm 👍 

Needs tests 🥴

**Comment by Kapn** [comment]
Needs tests 🥴

**Review by Kapn — CHANGES_REQUESTED** [review]
See PR Comment.

**Comment by rmonroe** [comment]
Testing
- Delete course
- disabling a course
- get user active courses
- get user inactive courses

**Review by Kapn — APPROVED** [review]

**Comment by Kapn** [comment]
Fixed #77

**Pull request merged**
