### PR TITLE
Squash migrations

### PR DESCRIPTION
**Pull request by Kapn**
Fixed migrations that were accidentally merged with PR #161

### CODE REVIEW

**Comment by rmonroe** [comment]
So are we not committing migrations, if so why don't we just add them to the .gitignore? This made a few extra to actually get the feature right

**Review by rmonroe — CHANGES_REQUESTED** [review]
So are we not committing migrations again, I thought this ended up being an issue? Or was this because of the repeats it took to get this one running?

**Comment by Kapn** [comment]
@rmonroe This PR squashes the 5 migration files that were created in that last PR into 1 file. Not sure what you are talking about not committing migrations, that is probably a separate conversation. This is currently our strat: (which we deviate from a bit usually haha)

image

**Comment by Kapn** [comment]
I see what you are saying, our strat says to delete the migrations before merging a PR. But that isn't a big deal since we don't have major schema changes or several devs making several model changes on the different PRs like we did in the early days, so we get away with it.

**Review by rmonroe — APPROVED** [review]
Ah I see makes sense

**Pull request merged**
