### PR TITLE
Fixes issue 156

### PR DESCRIPTION
**Pull request by andgates**

### CODE REVIEW

**Comment by rmonroe** [comment]
I have a fix for this one as well in IT_4.0, so...

**Comment by andgates** [comment]
> I have a fix for this one as well in IT_4.0, so...

thought the might happen, oops

**Review by Kapn — APPROVED** [review]

**Comment by rmonroe** [comment]
NOT APPROVED DUPLICATE

**Comment by rmonroe** [comment]
Fixed in PR IT_4.0

**Pull request closed without merging**
